apiVersion: v1
kind: Service
metadata:
  name: rcss-env-allocator
  namespace: rcss-gateway-dev
  labels:
    app: rcss-env-allocator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rcss-env-allocator
---
# Optional: Uncomment to expose via LoadBalancer
# apiVersion: v1
# kind: Service
# metadata:
#   name: rcss-env-allocator-ext
#   namespace: rcss-gateway-dev
#   labels:
#     app: rcss-env-allocator-ext
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     app: allocator
