#!/bin/sh
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$DIR/../../.registry/helios_common.sh"

BASE="$DIR/bin"
teamname="HELIOS2024"
version="19"
mc_parse_coach_args "$@"
mc_prepend_ld_path "$BASE/lib"
cd "$BASE" || exit 1
game_id=`date '+%Y%m%d-%H%M%S'`
common_opt=""
common_opt="$common_opt --common-conf $BASE/common.conf"
common_opt="$common_opt -h $host -t $teamname -v $version"
common_opt="$common_opt --game-id $game_id"
common_opt="$common_opt --strategy-dir $BASE/data/strategy"
common_opt="$common_opt --formation-dir $BASE/data/formations"
common_opt="$common_opt --setplay-dir $BASE/data/setplay"
common_opt="$common_opt --strategy-conf $BASE/data/strategy.conf"
common_opt="$common_opt --chain-search-method BestFirstSearch"
common_opt="$common_opt --evaluator-name Default"
common_opt="$common_opt --intercept-evaluator-name Default"
common_opt="$common_opt --max-chain-length 3 --max-evaluate-size 3000"
common_opt="$common_opt --svmrank-evaluator-model $BASE/data/svmrank_evaluator/model"
common_opt="$common_opt --svmrank-intercept-evaluator-model $BASE/data/svmrank_intercept_evaluator/model"
common_opt="$common_opt --neural-network-evaluator-dir $BASE/data/neural_network_evaluator/"
common_opt="$common_opt --center-forward-free-move-model $BASE/data/center_forward_free_move/model"
common_opt="$common_opt --svm-formation-classifier-model $BASE/data/svm_formation_classifier/svm.model"
common_opt="$common_opt --intercept-conf-dir $BASE/data/intercept_probability/"
common_opt="$common_opt --opponent-data-dir $BASE/data/opponent_data/"
common_opt="$common_opt --audio_shift 0"
coach_opt="--coach-config $BASE/coach.conf $common_opt -p $port"
coach_opt="$coach_opt --use_team_graphic on --team_graphic_file $BASE/data/team_logo-l.xpm"
coach_opt="$coach_opt --debug_server_host $debug_server_host --debug_server_port $debug_server_port"
coach_opt="$coach_opt $offline_logging $debugopt $debug_opt"
echo "dist-datetime = 20240721-1417-JST"
echo "coach options: $coach_opt"
exec "$BASE/helios_coach" $coach_opt
