apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-nexus-prime-env-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: oss
  volumeName: oss.nexus-prime.env-dev

