apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-nexus-prime-env-dev
  namespace: rcss-env-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Gi
  storageClassName: oss
  volumeName: oss.nexus-prime.env-dev

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-nexus-prime-env-allocator-dev
  namespace: rcss-gateway-dev
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
          storage: 3Gi
    storageClassName: oss
    volumeName: oss.nexus-prime.gateway.dev