apiVersion: v1
kind: ServiceAccount
metadata:
  name: rcss-env-allocator-sa
  namespace: rcss-gateway-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rcss-env-allocator-dev-role
  namespace: rcss-env-dev
rules:
  - apiGroups: ["allocation.agones.dev"]
    resources: ["gameserverallocations"]
    verbs: ["create", "get"]
  - apiGroups: ["agones.dev"]
    resources: ["fleets"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rcss-env-allocator-dev-sarb
  namespace: rcss-env-dev
subjects:
  - kind: ServiceAccount
    name: rcss-env-allocator-sa
    namespace: rcss-gateway-dev
roleRef:
  kind: Role
  name: rcss-env-allocator-dev-role
  apiGroup: rbac.authorization.k8s.io
